
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int READ = 10;
  public static final int IDENT = 19;
  public static final int ELSE = 8;
  public static final int STRINGCONST = 20;
  public static final int COMP = 16;
  public static final int WHILE = 9;
  public static final int END = 6;
  public static final int INTCONST = 18;
  public static final int BBINOP = 17;
  public static final int IF = 7;
  public static final int WRITE = 11;
  public static final int BEGIN = 5;
  public static final int COMMA = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int BUNOP = 12;
  public static final int ASSIGN = 13;
  public static final int RPAR = 4;
  public static final int BINOP = 14;
  public static final int LPAR = 3;
  public static final int BOOLCONST = 21;
  public static final int UNOP = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "LPAR",
  "RPAR",
  "BEGIN",
  "END",
  "IF",
  "ELSE",
  "WHILE",
  "READ",
  "WRITE",
  "BUNOP",
  "ASSIGN",
  "BINOP",
  "UNOP",
  "COMP",
  "BBINOP",
  "INTCONST",
  "IDENT",
  "STRINGCONST",
  "BOOLCONST"
  };
}

