/* The following code was generated by JFlex 1.3.5 on 6/8/18 10:18 PM */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 6/8/18 10:18 PM from the specification file
 * <tt>file:/C:/Users/Erfan/eclipse-workspace/compiler_cup/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int STRING = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\44\1\4"+
    "\1\16\2\0\1\45\1\0\1\32\1\33\1\40\1\10\1\31\1\37"+
    "\1\7\1\41\1\6\11\11\1\47\1\0\1\36\1\42\1\43\2\0"+
    "\1\14\3\14\1\14\1\14\5\5\1\15\5\5\1\5\1\5\1\5"+
    "\1\5\2\5\1\13\2\5\4\0\1\5\1\0\2\14\1\27\1\14"+
    "\1\22\1\20\2\5\1\17\2\5\1\12\1\5\1\21\1\24\2\5"+
    "\1\25\1\23\1\30\1\26\2\5\1\13\2\5\1\34\1\46\1\35"+
    "\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    40,    80,   120,    80,   160,   200,   240,   280,   320, 
      360,   400,   440,   480,   520,    80,    80,    80,    80,    80, 
      560,   320,    80,    80,   600,   640,   680,   720,   760,    80, 
      160,    80,   800,   840,   880,   840,    80,   200,   200,   920, 
      960,  1000,    80,    80,    80,    80,    80,    80,    80,   880, 
      200,  1040,  1080,  1120,   200,  1160,  1200,  1240,   200
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\4\7\1\14\1\15\1\16\1\7\1\17\6\7"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\50\3"+
    "\52\0\1\5\45\0\4\37\1\40\43\37\5\0\3\7"+
    "\1\0\5\7\1\0\12\7\25\0\1\41\1\42\1\0"+
    "\1\41\1\0\1\43\41\0\1\7\1\42\2\0\1\42"+
    "\4\7\1\0\12\7\25\0\1\41\1\44\1\0\1\13"+
    "\44\0\1\13\1\42\1\0\1\13\1\45\2\0\1\45"+
    "\32\0\2\14\1\0\45\14\5\0\3\7\1\0\5\7"+
    "\1\0\1\7\1\46\1\47\7\7\24\0\3\7\1\0"+
    "\5\7\1\0\5\7\1\50\1\7\1\51\2\7\24\0"+
    "\3\7\1\0\1\7\1\52\3\7\1\0\12\7\56\0"+
    "\1\53\2\0\1\54\47\0\1\55\47\0\1\56\47\0"+
    "\1\57\52\0\1\60\50\0\1\61\7\0\1\41\1\42"+
    "\1\0\1\41\44\0\1\42\2\0\1\42\44\0\1\62"+
    "\2\0\1\62\2\0\1\62\3\0\1\62\1\0\1\62"+
    "\4\0\1\62\25\0\3\7\1\0\5\7\1\0\6\7"+
    "\1\63\3\7\24\0\3\7\1\0\5\7\1\0\2\7"+
    "\1\64\7\7\24\0\3\7\1\0\5\7\1\0\4\7"+
    "\1\65\5\7\24\0\3\7\1\0\5\7\1\0\10\7"+
    "\1\66\1\7\24\0\3\7\1\0\5\7\1\0\3\7"+
    "\1\67\6\7\24\0\3\7\1\0\5\7\1\0\11\7"+
    "\1\70\24\0\3\7\1\0\5\7\1\0\1\71\11\7"+
    "\24\0\3\7\1\0\5\7\1\0\5\7\1\72\4\7"+
    "\24\0\3\7\1\0\5\7\1\0\2\7\1\73\7\7"+
    "\17\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9, 
     9,  9,  9,  9,  1,  1,  9,  9,  1,  1,  1,  1,  1,  9,  0,  9, 
     1,  1,  0,  0,  9,  1,  1,  1,  1,  1,  9,  9,  9,  9,  9,  9, 
     9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	
    StringBuffer string = new StringBuffer();

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, Object lexem){
	    return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }

    // private Symbol symbol(String name, int sym, Object val,int buflength) {
    //       Location left = new Location(yyline+1,yycolumn+yylength()-buflength,yychar+yylength()-buflength);
    //       Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
    //       return symbolFactory.newSymbol(name, sym, left, right,val);
    // }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[1280];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 142) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 50: 
          {  return symbol("for",FOR);  }
        case 60: break;
        case 47: 
          {  return symbol("and",AND);  }
        case 61: break;
        case 46: 
          {  return symbol("neq",NEQ);  }
        case 62: break;
        case 45: 
          {  return symbol("gtq",GTQ);  }
        case 63: break;
        case 43: 
          {  return symbol("leq",LEQ);  }
        case 64: break;
        case 26: 
          {  return symbol("not",NOT);  }
        case 65: break;
        case 16: 
          {  return symbol("(",LPAR);  }
        case 66: break;
        case 17: 
          {  return symbol(")",RPAR);  }
        case 67: break;
        case 18: 
          {  return symbol("{",BEGIN);  }
        case 68: break;
        case 23: 
          {  return symbol("div",DIV);  }
        case 69: break;
        case 6: 
        case 12: 
        case 13: 
        case 14: 
        case 39: 
        case 40: 
        case 41: 
        case 51: 
        case 52: 
        case 53: 
        case 55: 
        case 56: 
        case 57: 
          {  return symbol("Identifier",IDENT, yytext());  }
        case 70: break;
        case 54: 
          {  return symbol("else",ELSE);  }
        case 71: break;
        case 42: 
          {  return symbol("<-",ASSIGN);  }
        case 72: break;
        case 9: 
          {  return symbol("plus",PLUS);  }
        case 73: break;
        case 22: 
          {  return symbol("mult",MULT);  }
        case 74: break;
        case 31: 
          {  return symbol("STRINGCONST",STRINGCONST, yytext());  }
        case 75: break;
        case 29: 
          {  return symbol("colon",COLON); }
        case 76: break;
        case 15: 
          {  return symbol("comma",COMMA);  }
        case 77: break;
        case 21: 
          {  return symbol("minus",MINUS);  }
        case 78: break;
        case 10: 
        case 36: 
        case 49: 
          {  return symbol("INTCONST",INTCONST, new Integer(Integer.parseInt(yytext())));  }
        case 79: break;
        case 2: 
        case 5: 
        case 8: 
        case 24: 
        case 27: 
        case 28: 
          {  throw new Error("Parsing Failed! Illegal character ["+ yytext()+"] at line " + yyline + ", col " + yycolumn);  }
        case 80: break;
        case 48: 
          {  return symbol("or",OR);  }
        case 81: break;
        case 44: 
          {  return symbol("eq",EQ);  }
        case 82: break;
        case 38: 
          {  return symbol("in",IN);  }
        case 83: break;
        case 37: 
          {  return symbol("if",IF);  }
        case 84: break;
        case 19: 
          {  return symbol("}",END);  }
        case 85: break;
        case 20: 
          {  return symbol("le",LE);  }
        case 86: break;
        case 25: 
          {  return symbol("gt",GT);  }
        case 87: break;
        case 58: 
          {  return symbol("function",FUNCTION);  }
        case 88: break;
        case 7: 
        case 32: 
        case 33: 
          {  return symbol("FLOATCONST",FLOATCONST, new Float(Float.parseFloat(yytext())));  }
        case 89: break;
        case 11: 
          {  }
        case 90: break;
        case 3: 
        case 4: 
          {  }
        case 91: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
