/* The following code was generated by JFlex 1.6.1 */

package cup.example;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;




/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Lexer.jflex</tt>
 */
class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\1\1\1\1\1\22\0\1\0\1\45\1\4"+
    "\1\17\2\0\1\46\1\0\1\33\1\34\1\41\1\10\1\32\1\40"+
    "\1\7\1\42\1\12\11\11\1\50\1\0\1\37\1\43\1\44\2\0"+
    "\1\15\3\15\1\15\1\15\5\5\1\16\5\5\1\5\1\5\1\5"+
    "\1\5\2\5\1\14\2\5\4\0\1\5\1\0\2\15\1\30\1\15"+
    "\1\23\1\21\2\5\1\20\2\5\1\13\1\5\1\22\1\25\2\5"+
    "\1\26\1\24\1\31\1\27\2\5\1\14\2\5\1\35\1\47\1\36"+
    "\7\0\1\1\44\0\1\6\12\0\1\6\4\0\1\6\5\0\27\6"+
    "\1\0\37\6\1\0\u01ca\6\4\0\14\6\16\0\5\6\7\0\1\6"+
    "\1\0\1\6\21\0\165\6\1\0\2\6\2\0\4\6\1\0\1\6"+
    "\6\0\1\6\1\0\3\6\1\0\1\6\1\0\24\6\1\0\123\6"+
    "\1\0\213\6\1\0\255\6\1\0\46\6\2\0\1\6\7\0\47\6"+
    "\11\0\55\6\1\0\1\6\1\0\2\6\1\0\2\6\1\0\1\6"+
    "\10\0\33\6\5\0\3\6\35\0\13\6\5\0\112\6\4\0\146\6"+
    "\1\0\10\6\2\0\12\6\1\0\23\6\2\0\1\6\20\0\73\6"+
    "\2\0\145\6\16\0\66\6\4\0\1\6\5\0\56\6\22\0\34\6"+
    "\104\0\23\6\61\0\200\6\2\0\12\6\1\0\23\6\1\0\10\6"+
    "\2\0\2\6\2\0\26\6\1\0\7\6\1\0\1\6\3\0\4\6"+
    "\2\0\11\6\2\0\2\6\2\0\4\6\10\0\1\6\4\0\2\6"+
    "\1\0\5\6\2\0\14\6\17\0\3\6\1\0\6\6\4\0\2\6"+
    "\2\0\26\6\1\0\7\6\1\0\2\6\1\0\2\6\1\0\2\6"+
    "\2\0\1\6\1\0\5\6\4\0\2\6\2\0\3\6\3\0\1\6"+
    "\7\0\4\6\1\0\1\6\7\0\20\6\13\0\3\6\1\0\11\6"+
    "\1\0\3\6\1\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6"+
    "\2\0\12\6\1\0\3\6\1\0\3\6\2\0\1\6\17\0\4\6"+
    "\2\0\12\6\21\0\3\6\1\0\10\6\2\0\2\6\2\0\26\6"+
    "\1\0\7\6\1\0\2\6\1\0\5\6\2\0\11\6\2\0\2\6"+
    "\2\0\3\6\10\0\2\6\4\0\2\6\1\0\5\6\2\0\12\6"+
    "\1\0\1\6\20\0\2\6\1\0\6\6\3\0\3\6\1\0\4\6"+
    "\3\0\2\6\1\0\1\6\1\0\2\6\3\0\2\6\3\0\3\6"+
    "\3\0\14\6\4\0\5\6\3\0\3\6\1\0\4\6\2\0\1\6"+
    "\6\0\1\6\16\0\12\6\20\0\4\6\1\0\10\6\1\0\3\6"+
    "\1\0\27\6\1\0\20\6\3\0\10\6\1\0\3\6\1\0\4\6"+
    "\7\0\2\6\1\0\2\6\6\0\4\6\2\0\12\6\21\0\3\6"+
    "\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6\1\0\5\6"+
    "\2\0\11\6\1\0\3\6\1\0\4\6\7\0\2\6\7\0\1\6"+
    "\1\0\4\6\2\0\12\6\1\0\2\6\16\0\3\6\1\0\10\6"+
    "\1\0\3\6\1\0\51\6\2\0\10\6\1\0\3\6\1\0\5\6"+
    "\10\0\1\6\10\0\4\6\2\0\12\6\12\0\6\6\2\0\2\6"+
    "\1\0\22\6\3\0\30\6\1\0\11\6\1\0\1\6\2\0\7\6"+
    "\3\0\1\6\4\0\6\6\1\0\1\6\1\0\10\6\6\0\12\6"+
    "\2\0\2\6\15\0\72\6\5\0\17\6\1\0\12\6\47\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6"+
    "\1\0\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6"+
    "\1\0\15\6\1\0\3\6\2\0\5\6\1\0\1\6\1\0\6\6"+
    "\2\0\12\6\2\0\4\6\40\0\1\6\27\0\2\6\6\0\12\6"+
    "\13\0\1\6\1\0\1\6\1\0\1\6\4\0\12\6\1\0\44\6"+
    "\4\0\24\6\1\0\22\6\1\0\44\6\11\0\1\6\71\0\112\6"+
    "\6\0\116\6\2\0\46\6\1\0\1\6\5\0\1\6\2\0\53\6"+
    "\1\0\u014d\6\1\0\4\6\2\0\7\6\1\0\1\6\1\0\4\6"+
    "\2\0\51\6\1\0\4\6\2\0\41\6\1\0\4\6\2\0\7\6"+
    "\1\0\1\6\1\0\4\6\2\0\17\6\1\0\71\6\1\0\4\6"+
    "\2\0\103\6\2\0\3\6\40\0\20\6\20\0\125\6\14\0\u026c\6"+
    "\2\0\21\6\1\0\32\6\5\0\113\6\3\0\13\6\7\0\15\6"+
    "\1\0\7\6\13\0\25\6\13\0\24\6\14\0\15\6\1\0\3\6"+
    "\1\0\2\6\14\0\124\6\3\0\1\6\4\0\2\6\2\0\12\6"+
    "\41\0\3\6\2\0\12\6\6\0\130\6\10\0\53\6\5\0\106\6"+
    "\12\0\37\6\1\0\14\6\4\0\14\6\12\0\50\6\2\0\5\6"+
    "\13\0\54\6\4\0\32\6\6\0\12\6\46\0\34\6\4\0\77\6"+
    "\1\0\35\6\2\0\13\6\6\0\12\6\15\0\1\6\10\0\17\6"+
    "\101\0\114\6\4\0\12\6\21\0\11\6\14\0\164\6\14\0\70\6"+
    "\10\0\12\6\3\0\61\6\122\0\3\6\1\0\43\6\1\0\2\6"+
    "\6\0\366\6\6\0\u011a\6\2\0\6\6\2\0\46\6\2\0\6\6"+
    "\2\0\10\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6"+
    "\2\0\65\6\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6"+
    "\3\0\4\6\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6"+
    "\53\0\1\1\1\1\25\0\2\6\23\0\1\6\34\0\1\6\15\0"+
    "\1\6\20\0\15\6\63\0\41\6\21\0\1\6\4\0\1\6\2\0"+
    "\12\6\1\0\1\6\3\0\5\6\6\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\4\6\1\0\13\6\2\0\4\6\5\0\5\6\4\0"+
    "\1\6\21\0\51\6\u032d\0\64\6\u0716\0\57\6\1\0\57\6\1\0"+
    "\205\6\6\0\11\6\14\0\46\6\1\0\1\6\5\0\1\6\2\0"+
    "\70\6\7\0\1\6\17\0\30\6\11\0\7\6\1\0\7\6\1\0"+
    "\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\7\6\1\0\40\6\57\0\1\6\u01d5\0\3\6\31\0\17\6\1\0"+
    "\5\6\2\0\5\6\4\0\126\6\2\0\2\6\2\0\3\6\1\0"+
    "\132\6\1\0\4\6\5\0\51\6\3\0\136\6\21\0\33\6\65\0"+
    "\20\6\u0200\0\u19b6\6\112\0\u51cd\6\63\0\u048d\6\103\0\56\6\2\0"+
    "\u010d\6\3\0\34\6\24\0\63\6\1\0\12\6\1\0\37\6\1\0"+
    "\123\6\45\0\11\6\2\0\147\6\2\0\4\6\1\0\36\6\2\0"+
    "\2\6\105\0\61\6\30\0\64\6\14\0\105\6\13\0\12\6\6\0"+
    "\30\6\3\0\1\6\4\0\56\6\2\0\44\6\14\0\35\6\3\0"+
    "\101\6\16\0\13\6\6\0\37\6\1\0\67\6\11\0\16\6\2\0"+
    "\12\6\6\0\27\6\3\0\111\6\30\0\3\6\2\0\20\6\2\0"+
    "\5\6\12\0\6\6\2\0\6\6\2\0\6\6\11\0\7\6\1\0"+
    "\7\6\1\0\53\6\1\0\4\6\4\0\2\6\132\0\53\6\1\0"+
    "\2\6\2\0\12\6\6\0\u2ba4\6\14\0\27\6\4\0\61\6\u2104\0"+
    "\u016e\6\2\0\152\6\46\0\7\6\14\0\5\6\5\0\14\6\1\0"+
    "\15\6\1\0\5\6\1\0\1\6\1\0\2\6\1\0\2\6\1\0"+
    "\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0\14\6\4\0"+
    "\20\6\20\0\16\6\5\0\2\6\30\0\3\6\40\0\5\6\1\0"+
    "\207\6\23\0\12\6\7\0\32\6\4\0\1\6\1\0\32\6\13\0"+
    "\131\6\3\0\6\6\2\0\6\6\2\0\6\6\2\0\3\6\43\0"+
    "\14\6\1\0\32\6\1\0\23\6\1\0\2\6\1\0\17\6\2\0"+
    "\16\6\42\0\173\6\105\0\65\6\210\0\1\6\202\0\35\6\3\0"+
    "\61\6\17\0\1\6\37\0\40\6\20\0\33\6\5\0\53\6\5\0"+
    "\36\6\2\0\44\6\4\0\10\6\1\0\5\6\52\0\236\6\2\0"+
    "\12\6\126\0\50\6\10\0\64\6\234\0\u0137\6\11\0\26\6\12\0"+
    "\10\6\230\0\6\6\2\0\1\6\1\0\54\6\1\0\2\6\3\0"+
    "\1\6\2\0\27\6\12\0\27\6\11\0\37\6\141\0\26\6\12\0"+
    "\32\6\106\0\70\6\6\0\2\6\100\0\4\6\1\0\2\6\5\0"+
    "\10\6\1\0\3\6\1\0\33\6\4\0\3\6\4\0\1\6\40\0"+
    "\35\6\3\0\35\6\43\0\10\6\1\0\36\6\31\0\66\6\12\0"+
    "\26\6\12\0\23\6\15\0\22\6\156\0\111\6\u03b7\0\107\6\37\0"+
    "\12\6\17\0\74\6\25\0\31\6\7\0\12\6\6\0\65\6\1\0"+
    "\12\6\20\0\44\6\2\0\1\6\11\0\105\6\13\0\13\6\45\0"+
    "\22\6\1\0\45\6\170\0\73\6\5\0\12\6\7\0\3\6\1\0"+
    "\10\6\2\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0"+
    "\5\6\2\0\11\6\2\0\2\6\2\0\3\6\11\0\1\6\5\0"+
    "\7\6\2\0\7\6\3\0\5\6\u010b\0\106\6\1\0\1\6\10\0"+
    "\12\6\246\0\66\6\2\0\11\6\77\0\101\6\3\0\1\6\13\0"+
    "\12\6\46\0\70\6\10\0\12\6\u01d6\0\112\6\25\0\1\6\u01c0\0"+
    "\71\6\u0507\0\u0399\6\147\0\157\6\u0b91\0\u042f\6\u33d1\0\u0239\6\7\0"+
    "\37\6\1\0\12\6\146\0\36\6\2\0\5\6\13\0\67\6\11\0"+
    "\4\6\14\0\12\6\11\0\25\6\5\0\23\6\u0370\0\105\6\13\0"+
    "\57\6\20\0\21\6\u4060\0\2\6\u0bfe\0\153\6\5\0\15\6\3\0"+
    "\11\6\7\0\12\6\3\0\2\6\u14c6\0\5\6\3\0\6\6\10\0"+
    "\10\6\2\0\7\6\36\0\4\6\224\0\3\6\u01bb\0\125\6\1\0"+
    "\107\6\1\0\2\6\2\0\1\6\2\0\2\6\2\0\4\6\1\0"+
    "\14\6\1\0\1\6\1\0\7\6\1\0\101\6\1\0\4\6\2\0"+
    "\10\6\1\0\7\6\1\0\34\6\1\0\4\6\1\0\5\6\1\0"+
    "\1\6\3\0\7\6\1\0\u0154\6\2\0\31\6\1\0\31\6\1\0"+
    "\37\6\1\0\31\6\1\0\37\6\1\0\31\6\1\0\37\6\1\0"+
    "\31\6\1\0\37\6\1\0\31\6\1\0\10\6\2\0\62\6\u1000\0"+
    "\305\6\13\0\7\6\u0529\0\4\6\1\0\33\6\1\0\2\6\1\0"+
    "\1\6\2\0\1\6\1\0\12\6\1\0\4\6\1\0\1\6\1\0"+
    "\1\6\6\0\1\6\4\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\3\6\1\0\2\6\1\0\1\6\2\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\2\6\1\0\1\6\2\0"+
    "\4\6\1\0\7\6\1\0\4\6\1\0\4\6\1\0\1\6\1\0"+
    "\12\6\1\0\21\6\5\0\3\6\1\0\5\6\1\0\21\6\u0274\0"+
    "\32\6\6\0\32\6\6\0\32\6\u0e76\0\ua6d7\6\51\0\u1035\6\13\0"+
    "\336\6\u3fe2\0\u021e\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u06ed\0"+
    "\360\6\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\0\1\2\1\0\1\3\1\4\1\5"+
    "\1\6\3\2\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\0\1\20\1\21\2\0\1\22"+
    "\1\23\1\5\1\0\1\5\1\4\1\0\1\24\1\25"+
    "\3\2\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\4\1\35\3\2\1\36\3\2\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[55];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\244\0\315\0\366\0\u011f"+
    "\0\u0148\0\u0171\0\u019a\0\u01c3\0\u01ec\0\u01ec\0\u01ec\0\u01ec"+
    "\0\u01ec\0\u0215\0\315\0\u01ec\0\u01ec\0\u023e\0\u0267\0\u0290"+
    "\0\u02b9\0\u02e2\0\u01ec\0\u01ec\0\u030b\0\u030b\0\u0334\0\u01ec"+
    "\0\u035d\0\173\0\173\0\u0386\0\u03af\0\u03d8\0\u01ec\0\u01ec"+
    "\0\u01ec\0\u01ec\0\u01ec\0\u01ec\0\u01ec\0\u035d\0\173\0\u0401"+
    "\0\u042a\0\u0453\0\173\0\u047c\0\u04a5\0\u04ce\0\173";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[55];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\0\2\2\1\3\1\4\1\0\1\5\1\6\1\7"+
    "\1\10\4\4\1\11\1\12\1\13\1\4\1\14\6\4"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\2\0"+
    "\2\2\45\0\4\3\1\34\44\3\5\0\3\4\1\0"+
    "\6\4\1\0\12\4\24\0\1\4\3\0\2\35\4\4"+
    "\1\0\12\4\26\0\1\36\1\0\1\7\1\37\45\0"+
    "\1\35\1\0\2\7\1\40\2\0\1\40\41\0\1\35"+
    "\1\0\2\37\1\0\1\41\34\0\1\11\2\0\46\11"+
    "\5\0\3\4\1\0\6\4\1\0\1\4\1\42\1\43"+
    "\7\4\24\0\3\4\1\0\6\4\1\0\5\4\1\44"+
    "\1\4\1\45\2\4\24\0\3\4\1\0\2\4\1\46"+
    "\3\4\1\0\12\4\130\0\1\47\2\0\1\50\50\0"+
    "\1\51\50\0\1\52\50\0\1\53\53\0\1\54\51\0"+
    "\1\55\12\0\2\35\45\0\1\35\1\0\2\37\47\0"+
    "\2\56\2\0\1\56\3\0\1\56\1\0\1\56\4\0"+
    "\1\56\25\0\3\4\1\0\6\4\1\0\6\4\1\57"+
    "\3\4\24\0\3\4\1\0\6\4\1\0\2\4\1\60"+
    "\7\4\24\0\3\4\1\0\6\4\1\0\4\4\1\61"+
    "\5\4\24\0\3\4\1\0\6\4\1\0\10\4\1\62"+
    "\1\4\24\0\3\4\1\0\6\4\1\0\3\4\1\63"+
    "\6\4\24\0\3\4\1\0\6\4\1\0\11\4\1\64"+
    "\24\0\3\4\1\0\6\4\1\0\1\65\11\4\24\0"+
    "\3\4\1\0\6\4\1\0\5\4\1\66\4\4\24\0"+
    "\3\4\1\0\6\4\1\0\2\4\1\67\7\4\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1271];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\0\1\1\1\0\7\1\5\11\2\1"+
    "\2\11\1\0\2\1\2\0\2\11\1\1\1\0\1\1"+
    "\1\11\1\0\5\1\7\11\12\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[55];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuffer string = new StringBuffer();
    public Lexer(java.io.Reader in, ComplexSymbolFactory sf){
	this(in);
	    symbolFactory = sf;
    }
    ComplexSymbolFactory symbolFactory = new ComplexSymbolFactory();

  private Symbol symbol(String name, int sym) {
      return symbolFactory.newSymbol(name, sym, new Location(yyline+1,yycolumn+1,yychar), new Location(yyline+1,yycolumn+yylength(),yychar+yylength()));
  }

  private Symbol symbol(String name, int sym, Object val) {
      Location left = new Location(yyline+1,yycolumn+1,yychar);
      Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  private Symbol symbol(String name, int sym, Object val,int buflength) {
      Location left = new Location(yyline+1,yycolumn+yylength()-buflength,yychar+yylength()-buflength);
      Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  private void error(String message) {
    System.out.println("Error at line "+(yyline+1)+", column "+(yycolumn+1)+" : "+message);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2678) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {      return symbolFactory.newSymbol("EOF", EOF, new Location(yyline+1,yycolumn+1,yychar), new Location(yyline+1,yycolumn+1,yychar+1));
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 32: break;
          case 2: 
            { return symbol("Identifier",IDENT, yytext());
            }
          case 33: break;
          case 3: 
            { return symbol("plus",PLUS);
            }
          case 34: break;
          case 4: 
            { return symbol("INTCONST",INTCONST, new Integer(Integer.parseInt(yytext())));
            }
          case 35: break;
          case 5: 
            { return symbol("FLOATCONST",FLOATCONST, new Float(Float.parseFloat(yytext())));
            }
          case 36: break;
          case 6: 
            { return symbol("Comments",COMMENTS);
            }
          case 37: break;
          case 7: 
            { return symbol("comma",COMMA);
            }
          case 38: break;
          case 8: 
            { return symbol("(",LPAR);
            }
          case 39: break;
          case 9: 
            { return symbol(")",RPAR);
            }
          case 40: break;
          case 10: 
            { return symbol("{",BEGIN);
            }
          case 41: break;
          case 11: 
            { return symbol("}",END);
            }
          case 42: break;
          case 12: 
            { return symbol("le",LE);
            }
          case 43: break;
          case 13: 
            { return symbol("minus",MINUS);
            }
          case 44: break;
          case 14: 
            { return symbol("mult",MULT);
            }
          case 45: break;
          case 15: 
            { return symbol("div",DIV);
            }
          case 46: break;
          case 16: 
            { return symbol("gt",GT);
            }
          case 47: break;
          case 17: 
            { return symbol("not",NOT);
            }
          case 48: break;
          case 18: 
            { return symbol("colon",COLON);
            }
          case 49: break;
          case 19: 
            { return symbol("STRINGCONST",STRINGCONST, yytext());
            }
          case 50: break;
          case 20: 
            { return symbol("if",IF);
            }
          case 51: break;
          case 21: 
            { return symbol("if",IN);
            }
          case 52: break;
          case 22: 
            { return symbol("<-",ASSIGN);
            }
          case 53: break;
          case 23: 
            { return symbol("leq",LEQ);
            }
          case 54: break;
          case 24: 
            { return symbol("eq",EQ);
            }
          case 55: break;
          case 25: 
            { return symbol("gtq",GTQ);
            }
          case 56: break;
          case 26: 
            { return symbol("neq",NEQ);
            }
          case 57: break;
          case 27: 
            { return symbol("and",AND);
            }
          case 58: break;
          case 28: 
            { return symbol("or",OR);
            }
          case 59: break;
          case 29: 
            { return symbol("for",FOR);
            }
          case 60: break;
          case 30: 
            { return symbol("else",ELSE);
            }
          case 61: break;
          case 31: 
            { return symbol("function",FUNCTION);
            }
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
